#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    # Specify the cron job command
    cronjob='* * * * * /etc/doc_cli/maintence/rebuilder.sh >> /var/log/doc_cli/cron.log 2>&1'

    # Create a temporary file to store the current crontab entries
    temp_file=$(mktemp)

    # Export the current crontab to the temporary file
    crontab -l > "$temp_file"

    # Append the new cron job to the temporary file
    printf "%s\n" "$cronjob" >> "$temp_file"

    # Install the updated crontab from the temporary file
    crontab "$temp_file"

    # Clean up the temporary file
    rm "$temp_file"

fi
