services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file: ./.env
    depends_on:
      - certbot
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - /etc/letsencrypt:/etc/letsencrypt

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    network_mode: host
    command: certonly --standalone --preferred-challenges http --email nave1616@hotmail.com --agree-tos -d nave.autos --non-interactive --keep-until-expiring
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  database:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/db
      - ./app/configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    depends_on:
      database:
        condition: service_healthy
    build: ./app
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: ./.env
    environment:
      - MYSQL_HOST=database

volumes:
  db:
  certs:
