services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - certbot
    ports:
      - 80:80
      - 443:443
    env_file: ./.env
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - certs:/etc/letsencrypt
    volumes_from:
      - certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    network_mode: host
    entrypoint: /bin/sh
    command: -c "/certbot-scripts/certbot-entrypoint.sh"
    volumes:
      - ./certbot-entrypoint.sh:/certbot-scripts/certbot-entrypoint.sh
      - /etc/letsencrypt:/etc/letsencrypt
      - certs:/certs

  database:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/db
      - ./taskify/configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    depends_on:
      database:
        condition: service_healthy
    build: ./taskify
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: ./.env
    environment:
      - MYSQL_HOST=database

volumes:
  db:
  certs:
