#!/usr/bin/env bash
set -e

remove_old_cron() {
    crontab -l | grep -vF '/etc/ddeploy/maintence/rebuilder.sh' | crontab -
}

backup_old_conf() {
    conf_path="/etc/ddeploy/configs"
    conf_folder="/var/tmp/ddeploy/conf"
    rm -f $conf_path/variables.env
    if [[ ! -d "$conf_folder" ]]; then
        mkdir $conf_folder
    fi
    if [ ! -z "$(find "$conf_path" -mindepth 1 -maxdepth 1 -print -quit)" ]; then
        cp -f $conf_path/* $conf_folder
    fi
}

if  [ "$1" == "2" ] ; then
    echo "Remove old cronjobs ..."
    remove_old_cron
    echo "Backup configuration files ..."
    backup_old_conf
fi