#!/usr/bin/env bash
set -e

remove_cron() {
    crontab -l | grep -vF '/etc/ddeploy/maintence/rebuilder.sh' | crontab -
    crontab -l | grep -vF '/etc/ddeploy/maintence/backup.sh' | crontab -
}

backup_old_conf() {
    conf_folder="/var/tmp/ddeploy/conf"
    if [[ ! -d "$conf_folder" ]]; then
        mkdir -p $conf_folder
    fi
    if [ ! -z "$(find "/etc/ddeploy/configs" -mindepth 1 -maxdepth 1 -print -quit)" ]; then
        cp -f /etc/ddeploy/configs/* $conf_folder
    fi
}

if [ "$1" == "0" ]; then
    # Package removal
    backup_old_conf
    echo "Removing cronjobs ..."
    remove_cron
elif [ "$1" == "1" ]; then
    # Package upgrade
    backup_old_conf
fi