services:
  nginx_https:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./entrypoints/nginx_templates/:/etc/nginx/templates
      - certs:/etc/letsencrypt
      - html:/usr/share/nginx/html
    networks:
      - ddeployer-net

volumes:
  certs:
    name: certs
  html:
    name: html
networks:
  ddeployer-net:
    name: ddeployer-net
