services:
  nginx_https:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx_https
    ports:
      - 443:443
    volumes:
      - ./entrypoints/https/:/etc/nginx/templates
      - certs:/etc/letsencrypt
      - html:/usr/share/nginx/html
    networks:
      - ddeployer-net

  nginx_http:
    container_name: nginx_http
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./entrypoints/http/:/etc/nginx/templates
      - html:/usr/share/nginx/html
    networks:
      - ddeployer-net

volumes:
  certs:
  html:
networks:
  ddeployer-net:
    name: ddeployer-net
