#!/usr/bin/env bash
set -e

remove_old_cron(){
    crontab -l | grep -vF '/etc/ddeploy/maintence/rebuilder.sh' | crontab -
    crontab -l | grep -vF '/etc/ddeploy/maintence/cleaner.sh' | crontab -
}

backup_old_conf(){
    log_folder="/var/tmp/ddeploy/log"
    conf_folder="/var/tmp/ddeploy/conf"
    if [[ ! -d "$log_folder" ]]; then
        mkdir -p $log_folder
    fi
    if [[ ! -d "$conf_folder" ]]; then
        mkdir $conf_folder
    fi
    mv -f /etc/ddeploy/configs/* $conf_folder
    mv -f /var/log/ddeploy/* $log_folder
}

if [[ "$1" == "upgrade" ]]; then
    echo "Remove old cronjobs ..."
    remove_old_cron
    echo "Backup configuration files ..."
    backup_old_conf
fi