services:

  certbot:
    container_name: certbot-${NAME}
    image: certbot/certbot:latest
    env_file: ./.ddeploy.env
    entrypoint: sh -c 'while :; do certbot certonly --webroot -w /var/www/letsencrypt --preferred-challenges http-01 --email ${MAIL} --agree-tos -d ${CB_DOMAINS} --non-interactive --keep-until-expiring --expand; sleep 12h; done'
    volumes:
      - html:/var/www/letsencrypt
      - certs:/etc/letsencrypt
    networks:
      - ddeployer-net


  app:
    image: ${NAME}:${SHORT_COMMIT}
    container_name: app-${NAME}
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - GIT=${GIT}
        - BRANCH=${BRANCH}
        - COMMIT=${COMMIT}
        - BUILD=${BUILD}
        - RUN=${RUN}
        - PORT=${PORT}
        - IMAGE=${IMAGE}
    restart: unless-stopped
    env_file:
      - ./.ddeploy.env
    environment:
      - MYSQL_HOST=database
    networks:
      - ddeployer-net
      - db-network

volumes:
  certs:
    external: true
  html:
    external: true
networks:
  db-network:
  ddeployer-net:
    external: true
