services:

  certbot:
    container_name: certbot-${NAME}
    image: certbot/certbot:latest
    env_file: ./.ddeploy.env
    entrypoint: sh -c 'while :; do certbot certonly --webroot -w /var/www/letsencrypt --preferred-challenges http-01 --email ${MAIL} --agree-tos -d ${CB_DOMAINS} --non-interactive --keep-until-expiring --expand; sleep 12h; done'
    volumes:
      - html:/var/www/letsencrypt
      - certs:/etc/letsencrypt
    networks:
      - ddeployer-net

  database:
    container_name: mysql-${NAME}
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.ddeploy.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD="no"

    volumes:
      - db:/var/lib/mysql
      - ./entrypoint/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - db-network

  app:
    image: ${NAME}:${SHORT_COMMIT}
    container_name: app-${NAME}
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - GIT=${GIT}
        - BRANCH=${BRANCH}
        - COMMIT=${COMMIT}
        - BUILD=${BUILD}
        - RUN=${RUN}
        - PORT=${PORT}
        - IMAGE=${IMAGE}
    restart: unless-stopped
    env_file:
      - ./.ddeploy.env
    environment:
      - MYSQL_HOST=database
    networks:
      - ddeployer-net
      - db-network

volumes:
  db:
  certs:
    external: true
  html:
    external: true
networks:
  db-network:
  ddeployer-net:
    external: true
