name: Build Packages

on:
  workflow_call:
    inputs:
      version:
        required: false
        default: "0"
        type: string

jobs:
  build_debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set default version if not provided
        run: echo "VERSION=${VERSION:-0}" >> $GITHUB_ENV

      - name: Prepare Debian package
        run: |
          mv ./DEBIAN ./ddeploy
          sed -i "s/\$VERSION/${{ inputs.version }}/" ./ddeploy/DEBIAN/control
          sudo dpkg-deb --build ./ddeploy
          mv ddeploy.deb ddeploy_${{ inputs.version }}-1_all.deb
          tar -czvf ddeploy-debian-${{ inputs.version }}.tar.gz ddeploy_${{ inputs.version }}-1_all.deb

      - name: Create DEBIAN source Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-DEBIAN-source
          path: ddeploy-debian-${{ inputs.version }}.tar.gz

      - name: Create DEBIAN Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-deb
          path: ddeploy_${{ inputs.version }}-1_all.deb


  build_rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package lists and Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm build-essential dh-make

      - name: Set default version if not provided
        run: echo "VERSION=${VERSION:-0}" >> $GITHUB_ENV

      - name: Prepare RPM Package
        run: |
          sed -i "s/\$VERSION/${{ inputs.version }}/" ./rpmbuild/SPECS/ddeploy.spec
          echo '%_topdir %(pwd)/rpmbuild' > ~/.rpmmacros
          tar -czvf ddeploy.tar.gz ./ddeploy
          mv ddeploy.tar.gz ./rpmbuild/SOURCES/
          mkdir -p ./rpmbuild/{BUILDROOT,BUILD,RPMS}
          tar -czvf ddeploy-rpm-${{ inputs.version }}.tar.gz ./rpmbuild

      - name: Create RPM Source Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-RPM-source
          path: ddeploy-rpm-${{ inputs.version }}.tar.gz

      - name: Build RPM Package
        run: |
          rpmbuild -ba ./rpmbuild/SPECS/ddeploy.spec

      - name: Create RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-rpm
          path: rpmbuild/RPMS/noarch/*.rpm
