name: Build, Test, and Publish Deb Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package lists and Install dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y rpm build-essential dh-make

      - name: Build Debian Package
        run: |
          mv ./DEBIAN ./ddeploy
          sudo dpkg-deb --build ./ddeploy
          rm -rf ./ddeploy/DEBIAN

      - name: Create DEBIAN Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-deb
          path: ddeploy.deb


      - name: Prepare RPM Package
        run: |
            echo '%_topdir %(pwd)/rpmbuild' > ~/.rpmmacros
            tar -czvf ddeploy.tar.gz ./ddeploy
            mv ddeploy.tar.gz ./rpmbuild/SOURCES/
  
      - name: Build RPM Package
        run: |
            rpmbuild -ba ./rpmbuild/SPECS/ddeploy.spec
    
      - name: Create RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-rpm
          path: ./rpmbuild/RPMS/noarch/*.rpm
  
  
  test-debian:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
            name: ddeploy-deb

      - name: Update package lists
        run: sudo apt-get update && sudo apt-get install -y systemd build-essential dh-make

      - name: Install Docker and dependencies
        run: |
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker jq git cron

      - name: Install package
        run: |
            sudo dpkg -i ./ddeploy.deb

      - name: run tests
        run: |
            sudo bash ./tests/run.sh

  test-rpm:
    runs-on: centos-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
            name: ddeploy-rpm

      - name: Install dependencies for RPM testing
        run: |
            sudo yum install -y yum-utils
            sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin jq git cron

      - name: Install package
        run: |
            sudo rpm -i ./ddeploy.rpm

      - name: Run tests for RPM package
        run: |
            sudo bash ./tests/run-rpm.sh
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
        - name: Checkout code and Download Artifact
          uses: actions/checkout@v3
        
        - uses: actions/download-artifact@v4
          with:
            name: ddeploy
        
        - name: Commit and Push
          run: |
                git config user.email "github-actions@github.com"
                git config user.name "github-actions"
                git add ddeploy.deb
                git commit -m "Add ddeploy.deb"
                git push
          env:
            GH_PAT: ${{ secrets.GIT_TOKEN }}