name: Build, Test, and Publish Deb Package

on: [push]

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package lists and Install dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y rpm build-essential dh-make

      - name: Build Debian Package
        run: |
          mv ./DEBIAN ./ddeploy
          sudo dpkg-deb --build ./ddeploy
          tar -czvf ddeploy-debian-source.tar.gz ./ddeploy

      - name: Create DEBIAN source Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debian-source
          path: ddeploy-debian-source.tar.gz

      - name: Create DEBIAN Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-deb
          path: ddeploy.deb



  build-rpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Update package lists and Install dependencies
        run: |
         sudo apt-get update
         sudo apt-get install -y rpm build-essential dh-make

      - name: Prepare RPM Package
        run: |
          echo '%_topdir %(pwd)/rpmbuild' > ~/.rpmmacros
          tar -czvf ddeploy.tar.gz ./ddeploy
          mv ddeploy.tar.gz ./rpmbuild/SOURCES/
          tar -czvf ddeploy-rpm-source.tar.gz ./rpmbuild


      - name: Create RPM Source Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-rpm-source
          path: ddeploy-rpm-source.tar.gz

      - name: Build RPM Package
        run: |
          rpmbuild -ba ./rpmbuild/SPECS/ddeploy.spec

      - name: Create RPM Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ddeploy-rpm
          path: rpmbuild/RPMS/noarch/*.rpm

  test-debian:
    runs-on: ubuntu-latest
    needs: [build-debian,build-rpm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
            name: ddeploy-deb

      - name: Update package lists
        run: sudo apt-get update && sudo apt-get install -y systemd build-essential dh-make

      - name: Install Docker and dependencies
        run: |
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker jq git cron

      - name: Install package
        run: |
            sudo dpkg -i ./ddeploy.deb

      - name: run tests
        run: |
            sudo bash ./tests/run.sh
  
  publish-release:
    runs-on: ubuntu-latest
    needs: test-debian
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v4

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ddeploy-debian-source.tar.gz
            ddeploy-rpm-source.tar.gz
            rpmbuild/RPMS/noarch/*.rpm
            ddeploy.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

