name: Build, Test Deb & RPM Package

on:
  push:
  pull_request:

jobs:

  build_packages:
    uses: ./.github/workflows/build-packages.yml


  test_packages:
    needs: build_packages
    uses: ./.github/workflows/test-packages.yml