name: Build, Test Deb & RPM Package

on:
  pull_request:
    branches: ["main"]

jobs:
  build_packages:
    uses: ./.github/workflows/build-packages.yml

  test_packages:
    needs: build_packages
    uses: ./.github/workflows/test-packages.yml
