name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Write release version
        id: version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  build_packages:
    needs: get_version
    uses: ./.github/workflows/build-packages.yml
    with:
      VERSION: ${{ needs.get_version.outputs.version }}

  test_packages:
    needs: build_packages
    uses: ./.github/workflows/test-packages.yml

  publish_release:
    needs: test_packages
    uses: ./.github/workflows/publish-release.yml