name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build_packages:
    runs-on: ubuntu
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: version
        with:
          tagRegex: "v(.*)" 
          tagRegexGroup: 1
      - uses: ./.github/workflows/build-packages.yml
        with:
          VERSION: ${{ needs.version.outputs.tag }}

  test_packages:
    needs: build_packages
    uses: ./.github/workflows/test-packages.yml

  publish_release:
    needs: test_packages
    uses: ./.github/workflows/publish-release.yml