name: Publish Release

on:
  workflow_call:
    
jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download DEBIAN and RPM Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
          
      - name: Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Release with Notes
        uses: softprops/action-gh-release@v1

        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            artifacts/*/*.*
          tag_name: ${{ steps.release_drafter.outputs.tag_name }}
          name: ${{ steps.release_drafter.outputs.name }}
          body: ${{ steps.release_drafter.outputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
