name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker
      - name: Build package
        run: dpkg-deb --build --root-owner-group ddeploy
      - name: Install package
        run: sudo dpkg -i ddeploy_1.0_all.deb
      - name: cd tests folder
        working-directory: ./tests
        run: ./cli-test.sh

